FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc libpq-dev && apt-get clean

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/staticfiles
RUN python manage.py collectstatic --noinput || true

EXPOSE 8000

CMD ["gunicorn", "vote_x_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
