# Generated by Django 5.2.8 on 2025-11-16 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='guest_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'option', 'guest_ip')},
        ),
    ]
