# Generated by Django 5.2.8 on 2025-11-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_guest_votes',
            field=models.BooleanField(default=True),
        ),
    ]
